server:
  port: 8081
spring:
  application:
    name: grpc-client
#  jackson:
#    serialization:
#      fail-on-empty-beans: false

grpc:
  client:
    grpc-client:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

